#!/usr/bin/env python
import rospy
import pepper_bt.animation_node as anim_node


try:
    anim_node.launch_annimation()
except rospy.ROSInterruptException:
    print("pepper_animation is shutting down! + ros1")
except KeyboardInterrupt:
    print("pepper_animation is shutting down! +  ke1")
except RuntimeError:
    print("pepper_animation is shutting down! + run1")




 
