#!/usr/bin/env python

import pepper_bt.main as p
from pepper_bt.services import *
import pepper_bt.configs as cfg
import pepper_bt.constant as const
import pepper_bt.topics as topics
import rospy
from pepper_bt.main import *
import pepper_bt.audio_test   as a
import pepper_bt.test_audio as test


p.main()



