#!/usr/bin/env python

import pepper_bt.main as p
from pepper_bt.services import *
import pepper_bt.configs as cfg

# pepper = Pepper(cfg.IP_ADDRESS, cfg.PORT)
# pepper.start_recognizing_people()

p.main()

