IP_ADDRESS = "10.0.0.2"
PORT = 9559
REMOTE_IP = "10.0.0.20:8000"
INDEX_PATH = "/index.html"
RATE_PATH = "/rate.html"
WEB_URL = "http://" + REMOTE_IP + INDEX_PATH
RATE_URL = "http://" + REMOTE_IP + RATE_PATH

VOICE_SPEED_LOW = 80
